### ISSUE TITLE
Formato de datos

### ISSUE THREAD

**Issue by xocelot** [diegograziano/scriptable-dolar-blue.js#1]
![Image](https://user-images.githubusercontent.com/62994702/230128663-053f557b-0fa2-4a1d-821d-8eb450be844f.jpeg)

En iPhone 13 pro

**Comment by afidani** [comment]
https://api-dolar-argentina.herokuapp.com/api/dolarblue/ EStaba en Heroku pero esta caido.
Reemplazar con http://escuderokevin.com.ar:7070/api/dolarblue
